### ISSUE TITLE
TradeTokenUpdater not generating token

### ISSUE THREAD

**Issue by alexandruionita** [Arkarr/SourcemodASteambot#15]
The plugin throws the following error upon calling `sm_token`:
 
`sm_token XXXXX
L 07/03/2020 - 02:09:31: [SM] Exception reported: Client index 0 is invalid
L 07/03/2020 - 02:09:31: [SM] Blaming: ASteambot_TradeTokenUpdater.smx
L 07/03/2020 - 02:09:31: [SM] Call stack trace:
L 07/03/2020 - 02:09:31: [SM] [0] GetClientAuthId
L 07/03/2020 - 02:09:31: [SM] [1] Line 89, C:\Users\Arkarr\Documents\GitHub\SourcemodASteambot\Modules\Source\ASteambot_TradeTokenUpdater.sp::CMD_ASTradeToken`

**Comment by Arkarr** [comment]
Thanks forr the error report !
It is now fixed !
